namespace Star_041

/-!
# Comparison of `Agent041` against `Ref`

**`CPWL`.** `Agent041.CPWL n` asks for continuity plus a *finite family of affine
functions* `g : Fin m → ((Fin n → ℝ) → ℝ)` such that **at every point** `f x = g j x`
for some `j` (pointwise selection).  This is **not** the refutable
"neighbourhood agreement" family (`∀ᶠ y in nhds x, f y = g i y`), which would force
`f` to be globally affine: here the index `j` may vary from point to point with no
local constancy, so `fun x => max 0 (x 0)` *is* in `Agent041.CPWL 1`.

The two definitions in fact denote the same set.  `Ref ⊆ Agent` is immediate (forget
the polyhedra, keep the affine family).  `Agent ⊆ Ref` is true but genuinely hard: one
takes the finitely many hyperplanes `{g i = g j}`, notes that on each open cell of that
arrangement the closed sets `{f = g j}` are disjoint and cover a connected set, hence one
of them is everything, and then observes that the closed cells are polyhedra covering
`ℝⁿ`.  That argument is left as an honest `sorry` below.

**`ReLUn`.** Both files take *at most* `k` hidden layers, so no "exactly `k`" gap.  But
the recursions differ in direction: `Ref.ComputedBy` peels the *first* affine map off the
input side and recurses on a scalar-valued net, while `Agent041.NetFunc` peels the *last*
affine map off the output side and recurses on a vector-valued net.  They agree, but only
after an associativity/induction argument on the composition; `relun` is `sorry`-ed, with
the `k = 0` case proved outright as `relun_zero`.

**`depthBound`.** Identical up to `((n-1 : ℕ) : ℝ) = (n : ℝ) - 1`, proved below.
-/

/-- `Ref.IsAffine` and `Agent041.IsAffineScalar` are literally the same condition. -/
private theorem isAffine_iff {n : ℕ} (g : (Fin n → ℝ) → ℝ) :
    Ref.IsAffine g ↔ Agent041.IsAffineScalar g := Iff.rfl

/-- The easy direction: a polyhedral cover on which `f` is affine gives, at each point,
an affine function of the family agreeing with `f` there. -/
private theorem ref_subset_agent (n : ℕ) : Ref.CPWL n ⊆ Agent041.CPWL n := by
  intro f hf
  simp only [Ref.CPWL, Set.mem_setOf_eq, Ref.IsCPWL] at hf
  obtain ⟨hcont, m, P, g, -, hg, hcov, hagree⟩ := hf
  simp only [Agent041.CPWL, Set.mem_setOf_eq]
  refine ⟨hcont, m, g, fun j => (isAffine_iff (g j)).mp (hg j), fun x => ?_⟩
  have hx : x ∈ ⋃ i, P i := by rw [hcov]; trivial
  obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hx
  exact ⟨i, hagree i x hi⟩

/-- The hard direction.  True, but it needs the hyperplane-arrangement argument sketched
in the module docstring (connectedness of the open cells of the arrangement generated by
the finitely many sets `{g i = g j}`); not attempted here. -/
private theorem agent_subset_ref (n : ℕ) : Agent041.CPWL n ⊆ Ref.CPWL n := by
  sorry

theorem cpwl (n : ℕ) : Agent041.CPWL n = Ref.CPWL n :=
  Set.Subset.antisymm (agent_subset_ref n) (ref_subset_agent n)

/-- The depth-zero case of `relun`: with no hidden layer both sides are exactly the
affine functionals `ℝⁿ → ℝ`, the only difference being `Ref`'s bundled `Aff n 1` versus
`Agent041`'s unbundled matrix-and-vector. -/
theorem relun_zero (n : ℕ) : Agent041.ReLUn n 0 = Ref.ReLUn n 0 := by
  ext f
  constructor
  · rintro ⟨k', hk', F, hF, rfl⟩
    obtain rfl := Nat.le_zero.mp hk'
    obtain ⟨A, c, hAc⟩ := hF
    refine ⟨0, le_rfl, ⟨A, c⟩, fun x => ?_⟩
    simp [Ref.Aff.eval, hAc]
  · rintro ⟨j, hj, hcb⟩
    obtain rfl := Nat.le_zero.mp hj
    obtain ⟨T, hT⟩ := hcb
    refine ⟨0, le_rfl, fun x => T.M.mulVec x + T.c, ⟨T.M, T.c, fun x => rfl⟩, ?_⟩
    funext x
    exact hT x

/-- The two recursions build the same networks from opposite ends (`Ref` peels the input
layer, `Agent041` the output layer); reconciling them for general `k` needs an induction
that re-associates the composition, which is real work.  Only `k = 0` is proved
(`relun_zero`). -/
theorem relun (n k : ℕ) : Agent041.ReLUn n k = Ref.ReLUn n k := by
  sorry

theorem depth (n : ℕ) (hn : 3 ≤ n) : Agent041.depthBound n = Ref.depthBound n := by
  have h1 : (1 : ℕ) ≤ n := le_trans (by norm_num) hn
  have h : ((n - 1 : ℕ) : ℝ) = (n : ℝ) - 1 := by
    rw [Nat.cast_sub h1, Nat.cast_one]
  simp only [Agent041.depthBound, Ref.depthBound, h]

/-- Depends on the `Agent ⊆ Ref` inclusion for `CPWL` and on the full `relun`; both are
`sorry`-ed above, so this is `sorry`-ed rather than laundered through them. -/
theorem statement :
    (∀ n, 3 ≤ n → Agent041.CPWL n = Agent041.ReLUn n (Agent041.depthBound n)) ↔
    (∀ n, 3 ≤ n → Ref.CPWL n = Ref.ReLUn n (Ref.depthBound n)) := by
  sorry

end Star_041
